#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJ_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

APP_NAME="MMETestHost"
APP_UI_TEST_SCHEME="MMETestHost-leaks"
APP_RUNNER_NAME="$APP_UI_TEST_SCHEME-Runner"
APP_DIR="$PROJ_DIR"
APP_WORKSPACE="$PROJ_DIR/MapboxMobileEvents.xcodeproj"
APP_UI_TEST_PRINCIPAL_CLASS="PrincipalClass"
APP_UI_TEST_PRINCIPAL_CLASS_FILE="$PROJ_DIR/MMETestHostUITests/$APP_UI_TEST_PRINCIPAL_CLASS.m"
APP_UI_TEST_NAMES=( \
 	"$APP_UI_TEST_SCHEME/MMETestHostUITests" \
)

bash "$SCRIPT_DIR/memory-leak-tester/start"    \
        "$APP_NAME" \
        "$APP_RUNNER_NAME" \
        "$APP_WORKSPACE" \
        "$APP_UI_TEST_SCHEME" \
        ".memory-leak-tester-reports" \
        ".memory-leak-tester-build" \
        "iPhone X" \
        "$APP_UI_TEST_PRINCIPAL_CLASS_FILE" \
        "$APP_UI_TEST_PRINCIPAL_CLASS" \
        "$APP_UI_TEST_NAMES"
